### ISSUE TITLE
[Bug]: Packet 0/15 was larger than I expected

### ISSUE THREAD

**Issue by OsoaGH** [Fuzss/forgeconfigapiport#16]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19

### Mod Version (Required)

4.2.0

### Notes (Required)

When a user without the mod tries to join, they get this error:
![image](https://user-images.githubusercontent.com/33041004/185754010-0afbfe1b-1796-4a21-bd75-b078f9d5c7e3.png)
There doesn't appear to be any error on both the host and client's log. I don't think this is the same as #1 due to the different error but I might be wrong.

**Comment by Fuzss** [comment]
Thanks for reporting, fixing this is gonna be fun haha… 🙉

**Comment by OsoaGH** [comment]
yeah lol good luck

**Comment by DarkFireNinja** [comment]
Hey there, i don't mean to pressure you in any way, but this issue has not been fixed for almost 3 months already and i would really like if you could fix this bug so that i can use mods like Legendary Tooltips and a few other mods with my siblings (who don't have any mods installed) on a LAN world.

Thanks.

**Comment by Fuzss** [comment]
See https://github.com/Fuzss/forgeconfigapiport/issues/27.
