### ISSUE TITLE
[Crash]: Class com.electronwill.nightconfig.core.io.WritingMode does not have member field 'com.electronwill.nightconfig.core.io.WritingMode REPLACE_ATOMIC'

### ISSUE THREAD

**Issue by EightEggs** [Fuzss/forgeconfigapiport#65]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

0.16.0

### Mod Version(s) (Required)

v21.0.7

### Minimal Setup

No

### Notes (Required)

when adding certain another mod depending on this (e.g. SeasonHUD), it crashes due to some problem about `com.electronwill.nightconfig.core.io.WritingMode`.

may be useful: https://github.com/lanAnderson/SeasonHUD/issues/102

### Crash Report (Required)

https://github.com/user-attachments/files/16478785/crash-2024-08-03_16.49.43-client.txt

### latest.log (Optional)

https://github.com/user-attachments/files/16478788/latest.log

**Comment by Fuzss** [comment]
The underlying Night Config library has had a lot of changes recently. FCAP ships that latest version. SeasonHUD also includes Night Config, but an older version I’d assume. Fabric Loader automatically picks the latest version available, so there likely is a conflict there. 

So the solution probably is for SeasonHUD to update Night Config.

**Comment by lanAnderson** [comment]
Nah it's not me, I don't include it in the jar.  I think my mod was only in the crash log because I was the only one using ForgeConfigApiPort for configs. 

I wasn't able to replicate the crash until I added "Bodacious Berries", which @EightEggs also had installed, and it only crashes if it is the first  time generating the config. It looks like Bodacious Berries includes Nightconfig 3.6.6 in its jar and is the actual cause of the crash.

**Comment by ix0rai** [comment]
fixed on my side!

**Comment by EightEggs** [comment]
fixed
