### ISSUE TITLE
[Suggestion]: Loosen minecraft version constraint

### ISSUE THREAD

**Issue by Exopandora** [Fuzss/forgeconfigapiport#67]
### Mod Loader (Optional)

⸺

### Minecraft Version(s) (Optional)

Any

### Mod Version(s) (Optional)

Any

### Suggestion (Required)

The mod ships with a hard version constraint for minecraft, which does not allow loading the mod on any minecraft version, except for exactly the one it was compiled for. This makes updating the mod a requirement for each minor version. Furthermore, mod developers that depend on FCAP cannot start porting their mods to the latest version, because FCAP will prevent the game for booting. Yes, you can already fix all compiler issues, but you can't run the game yet. I would suggest relaxing the version constraint to at least the next patch version, as the mod is very likely to work across versions. This could be done the following way:

Fabric: `~${minecraftVersion}` or `>=${minecraftVersion}`
(Neo)Forge: `[${minecraftVersion},)`

**Comment by Fuzss** [comment]
I'm not a fan of this.

I had this set up initially, but there have been breaking changes in almost every Minecraft version since 1.19.2 that FCAP has been affected by (mostly regarding some method signatures relevant for Mixins on Fabric). I prefer recompiling for every new release.
Also devs did continuously use outdated versions with old apis like the 1.19 build was still used on 1.19.4 by some which was annoying to deal with, especially in regard to making breaking changes.

If you already want to port there is nothing stopping you from including the last available version for compiling against.
For Fabric runtime you can use [Dependency Overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides), Forge & NeoForge deliberately mark 1.21 mods as compatible for 1.21.1 as well.

But I generally aim to be quick with porting, the 1.21.1 port is out now.

**Comment by Exopandora** [comment]
Allright, thanks for your feedback!
